# Generated by Django 5.0.6 on 2025-08-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Исходные данные'),
        ),
    ]
