# Generated by Django 5.0.6 on 2025-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_options_transaction_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='OK', max_length=50, verbose_name='Статус операции'),
        ),
    ]
